package com.p38.anclab;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.res.ColorStateList;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.SeekBar;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;

import com.p38.anclab.profile.HeadphoneCalibration;
import com.p38.anclab.profile.MechanicalFrequency;
import com.p38.anclab.profile.ProfileStore;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/** Editable per-profile settings and vehicle mechanical-frequency models. */
public final class ProfileSettingsActivity extends Activity {
    private static final int BG=Color.rgb(9,13,18),CARD=Color.rgb(20,28,38),TEXT=Color.rgb(235,241,247),MUTED=Color.rgb(157,172,188),CYAN=Color.rgb(70,205,220),GREEN=Color.rgb(89,211,151),AMBER=Color.rgb(244,188,75);
    private ProfileStore profiles;

    @Override protected void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);profiles=new ProfileStore(AncRuntime.get(this).storage);if(AncRuntime.get(this).storage.isConnected())profiles.ensureDefaults();setContentView(build());}

    private View build(){ScrollView scroll=new ScrollView(this);LinearLayout root=column();root.setBackgroundColor(BG);root.setPadding(dp(14),dp(12),dp(14),dp(32));scroll.addView(root,new ScrollView.LayoutParams(-1,-2));LinearLayout title=row();Button back=iconButton("‹");back.setContentDescription("Back");back.setOnClickListener(v->finish());title.addView(back,new LinearLayout.LayoutParams(dp(48),dp(48)));TextView heading=text("PROFILE SETTINGS",22,TEXT);heading.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.addView(heading,new LinearLayout.LayoutParams(0,-2,1f));title.addView(info("Profiles","Each profile keeps its own name, description, output limit, route latency and mechanical-frequency models."));root.addView(title);for(String id:ProfileStore.PROFILE_IDS)root.addView(profilePanel(id),spaced());return scroll;}

    private LinearLayout profilePanel(String id){LinearLayout shell=card();Button header=secondary(profiles.loadProfileName(id)+"  ▸");shell.addView(header);LinearLayout body=column();body.setPadding(dp(3),dp(10),dp(3),0);body.setVisibility(View.GONE);shell.addView(body);header.setOnClickListener(v->{boolean open=body.getVisibility()!=View.VISIBLE;body.setVisibility(open?View.VISIBLE:View.GONE);header.setText(profiles.loadProfileName(id)+(open?"  ▾":"  ▸"));});
        body.addView(text("Display name",12,MUTED));EditText name=edit(profiles.loadProfileName(id),false);body.addView(name,match());body.addView(text("Description",12,MUTED),top());EditText description=edit(profiles.loadProfileDescription(id),true);body.addView(description,match());Button save=secondary("SAVE PROFILE");save.setOnClickListener(v->{if(profiles.saveProfileDetails(id,name.getText().toString(),description.getText().toString())){header.setText(profiles.loadProfileName(id)+"  ▾");toast("Profile saved");}else toast("Connect Documents/ANC before saving");});body.addView(save,top());
        TextView limit=text(profiles.loadAntiNoisePercent(id)+"% anti-noise limit",13,TEXT);limit.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(limit,top());SeekBar seek=new SeekBar(this);seek.setMax(100);seek.setProgress(profiles.loadAntiNoisePercent(id));seek.setProgressTintList(ColorStateList.valueOf(CYAN));seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int p,boolean user){limit.setText(p+"% anti-noise limit");if(user)profiles.saveAntiNoisePercent(id,p);}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});body.addView(seek,match());
        if(!ProfileStore.PROFILE_HEADPHONES.equals(id)){CheckBox broad=check("BROADBAND ANC",profiles.loadSpeculativeBroadband(id));broad.setOnCheckedChangeListener((b,on)->profiles.saveSpeculativeBroadband(id,on));body.addView(broad,top());body.addView(mechanicalEditor(id),top());}
        HeadphoneCalibration calibration=profiles.loadRouteCalibration(id);String calibrationSummary=calibration==null?"No stored latency profile":calibration.hasDelayStabilityMeasurement()?String.format(Locale.US,"Latency checks %.1f / %.1f ms · difference %.1f ms%s",calibration.delayCheckOneMs(),calibration.delayCheckTwoMs(),calibration.delayDifferenceMs(),calibration.latencyIsStable()?"":" · UNSTABLE"):String.format(Locale.US,"Legacy single latency check %.1f ms",calibration.delayMs());body.addView(text(calibrationSummary,12,calibration==null||!calibration.latencyIsStable()?AMBER:GREEN),top());Button use=secondary("MAKE CURRENT PROFILE");use.setOnClickListener(v->{profiles.saveCurrentProfile(id);toast(profiles.loadProfileName(id)+" selected");});body.addView(use,top());return shell;}

    private View mechanicalEditor(String profileId){LinearLayout shell=column();String title=ProfileStore.PROFILE_P38.equals(profileId)?"P38 MECHANICAL FREQ":"E46 MECHANICAL FREQ";LinearLayout header=row();TextView label=text("▸  "+title,13,CYAN);label.setTypeface(Typeface.DEFAULT,Typeface.BOLD);header.addView(label,new LinearLayout.LayoutParams(0,-2,1f));header.addView(info(title,"Every model stores a name, anchor frequency, detected reference value and source type. Live telemetry predicts its current frequency and the microphone fine-tunes it."));shell.addView(header);LinearLayout body=column();body.setVisibility(View.GONE);shell.addView(body);header.setOnClickListener(v->{boolean open=body.getVisibility()!=View.VISIBLE;body.setVisibility(open?View.VISIBLE:View.GONE);label.setText((open?"▾  ":"▸  ")+title);});List<ModelEditor> editors=new ArrayList<>();List<MechanicalFrequency> models=profiles.loadMechanicalFrequencies(profileId);LinearLayout prop=group("PROPSHAFT",false),engine=group("CRANKSHAFT / ENGINE",false),other=group("OTHER",false);body.addView(prop,top());body.addView(engine,top());body.addView(other,top());for(MechanicalFrequency model:models){LinearLayout target=model.id().contains("prop")?groupBody(prop):model.id().contains("crank")||model.id().contains("engine")?groupBody(engine):groupBody(other);addModelEditor(target,editors,model);}Button add=secondary("ADD MECHANICAL FREQUENCY");add.setOnClickListener(v->addModelEditor(groupBody(other),editors,new MechanicalFrequency("model-"+System.currentTimeMillis(),"New frequency",50.0,0.0,MechanicalFrequency.SourceType.FIXED,true)));body.addView(add,top());Button save=secondary("SAVE MECHANICAL FREQUENCIES");save.setOnClickListener(v->{List<MechanicalFrequency> values=new ArrayList<>();try{for(ModelEditor editor:editors)if(editor.root.getParent()!=null)values.add(editor.value());if(profiles.saveMechanicalFrequencies(profileId,values))toast("Mechanical frequencies saved");else toast("Could not save mechanical frequencies");}catch(IllegalArgumentException e){toast(e.getMessage());}});body.addView(save,top());return shell;}

    private LinearLayout group(String title,boolean open){LinearLayout shell=card();Button header=secondary(title+(open?"  ▾":"  ▸"));LinearLayout body=column();body.setVisibility(open?View.VISIBLE:View.GONE);shell.addView(header);shell.addView(body);header.setOnClickListener(v->{boolean show=body.getVisibility()!=View.VISIBLE;body.setVisibility(show?View.VISIBLE:View.GONE);header.setText(title+(show?"  ▾":"  ▸"));});shell.setTag(body);return shell;}
    private LinearLayout groupBody(LinearLayout group){return (LinearLayout)group.getTag();}

    private void addModelEditor(LinearLayout parent,List<ModelEditor> editors,MechanicalFrequency model){LinearLayout root=card();CheckBox enabled=check("ENABLED",model.enabled());root.addView(enabled);root.addView(text("Name",11,MUTED),top());EditText name=edit(model.name(),false);root.addView(name);LinearLayout labels=row();labels.addView(text("Frequency (Hz)",11,MUTED),new LinearLayout.LayoutParams(0,-2,1f));labels.addView(text("Detected number",11,MUTED),new LinearLayout.LayoutParams(0,-2,1f));root.addView(labels,top());LinearLayout numbers=row();EditText frequency=number(model.frequencyHz());EditText detected=number(model.detectedNumber());numbers.addView(frequency,new LinearLayout.LayoutParams(0,-2,1f));numbers.addView(detected,new LinearLayout.LayoutParams(0,-2,1f));root.addView(numbers);root.addView(text("Detected number type",11,MUTED),top());Spinner type=new Spinner(this);ArrayAdapter<MechanicalFrequency.SourceType> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,MechanicalFrequency.SourceType.values());type.setAdapter(adapter);type.setSelection(model.detectedNumberType().ordinal());root.addView(type);Button remove=secondary("REMOVE");remove.setOnClickListener(v->parent.removeView(root));root.addView(remove,top());ModelEditor editor=new ModelEditor(root,model.id(),enabled,name,frequency,detected,type);editors.add(editor);parent.addView(root,top());}

    private final class ModelEditor{final View root;final String id;final CheckBox enabled;final EditText name,frequency,detected;final Spinner type;ModelEditor(View r,String i,CheckBox e,EditText n,EditText f,EditText d,Spinner t){root=r;id=i;enabled=e;name=n;frequency=f;detected=d;type=t;}MechanicalFrequency value(){double hz=parse(frequency,"Frequency"),reference=parse(detected,"Detected number");if(hz<8||hz>200)throw new IllegalArgumentException("Frequency must be between 8 and 200 Hz");return new MechanicalFrequency(id,name.getText().toString().trim(),hz,reference,(MechanicalFrequency.SourceType)type.getSelectedItem(),enabled.isChecked());}}
    private static double parse(EditText field,String label){try{return Double.parseDouble(field.getText().toString().trim());}catch(Exception e){throw new IllegalArgumentException(label+" is not a valid number");}}

    private EditText edit(String value,boolean multiline){EditText field=new EditText(this);field.setText(value);field.setTextColor(TEXT);field.setHintTextColor(MUTED);field.setSingleLine(!multiline);field.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES|(multiline?InputType.TYPE_TEXT_FLAG_MULTI_LINE:0));return field;}
    private EditText number(double value){EditText field=edit(String.format(Locale.US,"%.4f",value),false);field.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL|InputType.TYPE_NUMBER_FLAG_SIGNED);return field;}
    private TextView info(String title,String message){TextView v=text("ⓘ",19,CYAN);v.setGravity(Gravity.END);v.setPadding(dp(8),dp(3),dp(8),dp(3));v.setOnClickListener(x->new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show());return v;}
    private CheckBox check(String label,boolean checked){CheckBox v=new CheckBox(this);v.setText(label);v.setTextColor(TEXT);v.setChecked(checked);v.setButtonTintList(ColorStateList.valueOf(CYAN));return v;}
    private LinearLayout column(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.VERTICAL);return v;}private LinearLayout row(){LinearLayout v=new LinearLayout(this);v.setOrientation(LinearLayout.HORIZONTAL);v.setGravity(Gravity.CENTER_VERTICAL);return v;}private LinearLayout card(){LinearLayout v=column();v.setPadding(dp(12),dp(11),dp(12),dp(11));GradientDrawable bg=new GradientDrawable();bg.setColor(CARD);bg.setCornerRadius(dp(13));v.setBackground(bg);return v;}private TextView text(String value,float size,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);return v;}private Button secondary(String label){Button v=new Button(this);v.setText(label);v.setTextColor(TEXT);v.setTextSize(13);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);GradientDrawable bg=new GradientDrawable();bg.setColor(Color.rgb(39,55,70));bg.setCornerRadius(dp(9));v.setBackground(bg);return v;}private Button iconButton(String label){Button v=secondary(label);v.setTextSize(28);v.setPadding(0,0,0,0);return v;}private LinearLayout.LayoutParams match(){return new LinearLayout.LayoutParams(-1,-2);}private LinearLayout.LayoutParams spaced(){LinearLayout.LayoutParams p=match();p.topMargin=dp(9);return p;}private LinearLayout.LayoutParams top(){LinearLayout.LayoutParams p=match();p.topMargin=dp(8);return p;}private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}private void toast(String message){Toast.makeText(this,message,Toast.LENGTH_SHORT).show();}
}
